# Generated by Django 3.1.5 on 2021-01-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_postpics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('for_moderate', 'Ожидает Модерации'), ('published', 'Опубликован')], default='for_moderate', max_length=255, verbose_name='Статус'),
        ),
    ]
